In [1]:
import cPickle as pickle
import pandas as pd, numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [2]:
test = pd.read_csv('./test.csv')

In [3]:
test = pd.DataFrame([['1', 'Hey'],
                     ['2', 'hi'],
                     ['3', 'whats up?'],
                     ['4', 'nothing much, Im depressed'],
                     ['5','My teacher hates me, never listens to my reasoning'],
                     ['6','I feel like murdering her'],
                     ['7','hey dont say that'],
                     ['8','what am I gonna do about her?'],
                     ['9','idk'],
                     ['10','I\'ll probably murder her']
                    ], columns=['id', 'comment_text'])

In [4]:
test.head()

id                                       comment_text
0  1                                                Hey
1  2                                                 hi
2  3                                          whats up?
3  4                         nothing much, Im depressed
4  5  My teacher hates me, never listens to my reaso...

In [5]:
test['comment_text'].fillna("unknown", inplace=True)

In [6]:
import re,string
re_tok = re.compile(re.escape(string.punctuation))

In [7]:
def tokenize(s): return re_tok.sub(r' \1 ', s).split()

In [43]:
vec = TfidfVectorizer(ngram_range=(1,2), tokenizer=tokenize,
               min_df=3, max_df=0.9, strip_accents='unicode', use_idf=1,
               smooth_idf=1, sublinear_tf=1 )
vec = pickle.load(open('/home/ammar/study/8th semester/FYP/toxic comments/vec', 'rb'))
test_term_doc = vec.transform(test['comment_text'])

In [44]:
def pr(y_i, y):
    p = x[y==y_i].sum(0)
    return (p+1) / ((y==y_i).sum()+1)
x = trn_term_doc
test_x = test_term_doc

In [45]:
label_cols = ['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']
preds = np.zeros((len(test), len(label_cols)))

In [46]:
for i, j in enumerate(label_cols):
    print('fit', j)
    m = pickle.load(open('/home/ammar/study/8th semester/FYP/toxic comments/model'+ str(i), 'rb'))
    r = pickle.load(open('/home/ammar/study/8th semester/FYP/toxic comments/r'+ str(i), 'rb'))
    print r
    preds[:,i] = m.predict_proba(test_x.multiply(r))[:,1]

('fit', 'toxic')
[[0.57415495 1.24205391 0.9865223  ... 1.79746125 0.75787254 0.75787254]]
('fit', 'severe_toxic')
[[0.99404422 3.59278685 2.95475165 ... 3.66620322 3.10860548 3.10860548]]
('fit', 'obscene')
[[0.55067865 2.09367642 1.53332723 ... 1.9551819  1.39758416 1.39758416]]
('fit', 'threat')
[[1.61549549 4.8033878  4.1653526  ... 4.87680417 4.31920643 4.31920643]]
('fit', 'insult')
[[0.65812021 1.95563576 1.70010415 ... 2.02905213 1.47145439 1.47145439]]
('fit', 'identity_hate')
[[0.55819766 3.72074054 3.08270534 ... 3.79415691 3.23655917 3.23655917]]


In [47]:
print r.shape
print m
print test_x.shape

(1, 440978)
LogisticRegression(C=4, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)
(10, 440978)


In [48]:
submid = pd.DataFrame({'id': test["id"]})
submission = pd.concat([submid, pd.DataFrame(preds, columns = label_cols)], axis=1)

In [49]:
test

id                                      comment_text
0   1             I hate my school, Ill murder everyone
1   2                                     Ill join ISIS
2   3  Dr Tariq is such a dick! Changes fyp every month
3   4                              Love the way you lie
4   5                                  Lets blow up IBA
5   6                                 I hate my teacher
6   7                        Where can I buy explosives
7   8                                 I do not hate IBA
8   9                                   I dont like you
9  10                                     How to murder

In [1]:
submission

NameError: name 'submission' is not defined